### ISSUE TITLE
pip install installs version 0.2.1 instead of the latest 0.5.0

### ISSUE THREAD

**Issue by selimt** [manjitkumar/drf-url-filters#32]
When we pip install this package we get an older version (0.2.1) which is not compatible with Python 3.

Thanks.

**Comment by manjitkumar** [comment]
@selimt I was not able to push the lastest release to pypi after a multiple attempts because of some error. Still you can download it from github only using pip install https://github.com/manjitkumar/drf-url-filters/archive/v0.5.0.tar.gz

Also, there was a problem with this release if you are using python3, I have made a patch to that in PR #33 which will be released under tag v0.5.1 by the end of day (Today June 20th, 2017)

**Comment by manjitkumar** [comment]
Now you can download latest version of `drf-url-filters` from PyPI using command: `pip install drf-url-filters`.
